/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Francesco' at '19/02/17 15:32' with Gradle 2.9
 *
 * @author Francesco, @date 19/02/17 15:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
